### ISSUE TITLE
Please change Master to Latest

### ISSUE THREAD

**Issue by shaho1090** [Tanya-WebDev/configuration-files-for-the-symfony-project#1]
Hello Dear Tanya,

Thank you for making the configuration files. I just used it and faced an issue I wanted to tell you about; please change the ENV EXT_AMQP_VERSION=master to the latest since it was changed in the reference repository.

I forked and fixed the issues and made the pull request for it. 

Many Thanks

**Comment by Tanya-WebDev** [comment]
Thank you too!
